INSERT INTO BOOK(NAME, PRICE, PROFESSOR) VALUES('It Ends With Her', '600', 'Brianna Labuskes');
INSERT INTO BOOK(NAME, PRICE, PROFESSOR) VALUES('When Never Comes', '580', 'Barbara Davis');
INSERT INTO BOOK(NAME, PRICE, PROFESSOR) VALUES('An American Princess:The Many Lives of Allene Tew', '700', 'Annejet van der Zijl');
INSERT INTO MUSIC(NAME, PRICE, LENGTH) VALUES('My Heart Will Go On', '550', '230');
INSERT INTO MUSIC(NAME, PRICE, LENGTH) VALUES('Take Me Home, Country Road', '550', '230');
INSERT INTO MUSIC(NAME, PRICE, LENGTH) VALUES('You Raise Me Up', '450', '270');
INSERT INTO MOVIE(NAME, CATEGORY, YEAR) VALUES('Doctor Strange', 'Action', '2016');
INSERT INTO MOVIE(NAME, CATEGORY, YEAR) VALUES('Jumanji', 'Adventure', '2017');
INSERT INTO MOVIE(NAME, CATEGORY, YEAR) VALUES('A Quiet Place', 'Horror', '2018');
