INSERT INTO BOOK(NAME, PRICE, PROFESSOR, VIEW_COUNT, COLLEGE) VALUES('G', '600', 'Brianna Labuskes', 0, '管理學院');
INSERT INTO BOOK(NAME, PRICE, PROFESSOR, VIEW_COUNT, COLLEGE) VALUES('H', '580', 'Barbara Davis', 0, '公共衛生學院');
INSERT INTO BOOK(NAME, PRICE, PROFESSOR, VIEW_COUNT, COLLEGE) VALUES('I', '700', 'Annejet van der Zijl', 0,'公共衛生學院');
INSERT INTO BOOK(NAME, PRICE, PROFESSOR, VIEW_COUNT, COLLEGE) VALUES('A', '600', 'Brianna Labuskes', 3, '電機資訊學院');
INSERT INTO BOOK(NAME, PRICE, PROFESSOR, VIEW_COUNT, COLLEGE) VALUES('AB', '580', 'Barbara Davis', 2, '公共衛生學院');
INSERT INTO BOOK(NAME, PRICE, PROFESSOR, VIEW_COUNT, COLLEGE) VALUES('AC', '700', 'Annejet van der Zijl', 1, '公共衛生學院');
INSERT INTO BOOK(NAME, PRICE, PROFESSOR, VIEW_COUNT, COLLEGE) VALUES('A', '600', 'Brianna Labuskes', 3, '文學院');
INSERT INTO BOOK(NAME, PRICE, PROFESSOR, VIEW_COUNT, COLLEGE) VALUES('E', '580', 'Barbara Davis', 2, '管理學院');
INSERT INTO BOOK(NAME, PRICE, PROFESSOR, VIEW_COUNT, COLLEGE) VALUES('F', '700', 'Annejet van der Zijl', 1, '工學院');
INSERT INTO BOOK(NAME, PRICE, PROFESSOR, VIEW_COUNT, COLLEGE) VALUES('H', '400', 'Annejet van der Zijl', 1, '工學院');
INSERT INTO BOOK(NAME, PRICE, PROFESSOR, VIEW_COUNT, COLLEGE) VALUES('I', '950', 'Annejet van der Zijl', 1, '工學院');
INSERT INTO BOOK(NAME, PRICE, PROFESSOR, VIEW_COUNT, COLLEGE) VALUES('J', '730', 'Annejet van der Zijl', 1, '管理學院');


--INSERT INTO MUSIC(NAME, PRICE, LENGTH) VALUES('My Heart Will Go On', '550', '230');
--INSERT INTO MUSIC(NAME, PRICE, LENGTH) VALUES('Take Me Home, Country Road', '550', '230');
--INSERT INTO MUSIC(NAME, PRICE, LENGTH) VALUES('You Raise Me Up', '450', '270');
--INSERT INTO MOVIE(NAME, CATEGORY, YEAR) VALUES('Doctor Strange', 'Action', '2016');
--INSERT INTO MOVIE(NAME, CATEGORY, YEAR) VALUES('Jumanji', 'Adventure', '2017');
--INSERT INTO MOVIE(NAME, CATEGORY, YEAR) VALUES('A Quiet Place', 'Horror', '2018');
