--INSERT INTO BOOK(NAME, PRICE, PROFESSOR, VIEW_COUNT, COLLEGE) VALUES('G', '600', 'Brianna Labuskes', 0, '管理學院');
--INSERT INTO BOOK(NAME, PRICE, PROFESSOR, VIEW_COUNT, COLLEGE) VALUES('H', '580', 'Barbara Davis', 0, '公共衛生學院');
--INSERT INTO BOOK(NAME, PRICE, PROFESSOR, VIEW_COUNT, COLLEGE) VALUES('I', '700', 'Annejet van der Zijl', 0,'公共衛生學院');
--INSERT INTO BOOK(NAME, PRICE, PROFESSOR, VIEW_COUNT, COLLEGE) VALUES('A', '600', 'Brianna Labuskes', 3, '電機資訊學院');
--INSERT INTO BOOK(NAME, PRICE, PROFESSOR, VIEW_COUNT, COLLEGE) VALUES('AB', '580', 'Barbara Davis', 2, '公共衛生學院');
--INSERT INTO BOOK(NAME, PRICE, PROFESSOR, VIEW_COUNT, COLLEGE) VALUES('AC', '700', 'Annejet van der Zijl', 1, '公共衛生學院');
--INSERT INTO BOOK(NAME, PRICE, PROFESSOR, VIEW_COUNT, COLLEGE) VALUES('A', '600', 'Brianna Labuskes', 3, '文學院');
--INSERT INTO BOOK(NAME, PRICE, PROFESSOR, VIEW_COUNT, COLLEGE) VALUES('E', '580', 'Barbara Davis', 2, '管理學院');
--INSERT INTO BOOK(NAME, PRICE, PROFESSOR, VIEW_COUNT, COLLEGE) VALUES('F', '700', 'Annejet van der Zijl', 1, '工學院');
--INSERT INTO BOOK(NAME, PRICE, PROFESSOR, VIEW_COUNT, COLLEGE) VALUES('H', '400', 'Annejet van der Zijl', 1, '工學院');
--INSERT INTO BOOK(NAME, PRICE, PROFESSOR, VIEW_COUNT, COLLEGE) VALUES('I', '950', 'Annejet van der Zijl', 1, '工學院');
--INSERT INTO BOOK(NAME, PRICE, PROFESSOR, VIEW_COUNT, COLLEGE) VALUES('J', '730', 'Annejet van der Zijl', 1, '管理學院');

INSERT INTO BOOK(NAME, PRICE, PROFESSOR, COURSE_NAME, COLLEGE, NOTES_ON, HOW_NEW, MESSAGES, IMAGE_FILE) VALUES ('Fundamentals of Corporate Finance',980,'財務管理','盧秋玲','管理學院','Y','100','完全沒有使用過','1.jpg');
INSERT INTO BOOK(NAME, PRICE, PROFESSOR, COURSE_NAME, COLLEGE, NOTES_ON, HOW_NEW, MESSAGES, IMAGE_FILE) VALUES ('The Economics of Money, Banking, and Financial Markets',1120,'貨幣銀行學','陳思寬','管理學院','N','50','五成	舊舊的感覺，但完整無破損缺頁','2.jpg');
INSERT INTO BOOK(NAME, PRICE, PROFESSOR, COURSE_NAME, COLLEGE, NOTES_ON, HOW_NEW, MESSAGES, IMAGE_FILE) VALUES ('Statistics for Business and Economics',790,'統計學','游孝元','管理學院','Y','70','七成	品質佳','3.jpg');
INSERT INTO BOOK(NAME, PRICE, PROFESSOR, COURSE_NAME, COLLEGE, NOTES_ON, HOW_NEW, MESSAGES, IMAGE_FILE) VALUES ('經濟學原理',750,'經濟學原理與實習','吳聰敏','社會科學院','Y','90','九成	只有打開過兩次','4.jpg');
INSERT INTO BOOK(NAME, PRICE, PROFESSOR, COURSE_NAME, COLLEGE, NOTES_ON, HOW_NEW, MESSAGES, IMAGE_FILE) VALUES ('Pediatrics',880,'小兒科臨床實習','黃立民','醫學院','Y','100','完全沒有使用過','5.jpg');
INSERT INTO BOOK(NAME, PRICE, PROFESSOR, COURSE_NAME, COLLEGE, NOTES_ON, HOW_NEW, MESSAGES, IMAGE_FILE) VALUES ('Marketing Management',1040,'行銷管理','謝明慧','管理學院','N','50','完全沒有使用過','6.jpg');
INSERT INTO BOOK(NAME, PRICE, PROFESSOR, COURSE_NAME, COLLEGE, NOTES_ON, HOW_NEW, MESSAGES, IMAGE_FILE) VALUES ('微積分乙',970,'微積分乙','翁秉仁','管理學院','N','90','完全沒有使用過','7.jpg');
INSERT INTO BOOK(NAME, PRICE, PROFESSOR, COURSE_NAME, COLLEGE, NOTES_ON, HOW_NEW, MESSAGES, IMAGE_FILE) VALUES ('實用商法',890,'商事法','洪瑞燦','管理學院','N','100','完全沒有使用過','8.jpg');
	

--INSERT INTO BOOK(NAME, PRICE, PROFESSOR, COURSE_NAME, COLLEGE, NOTES_ON, HOW_NEW, MESSAGES, IMAGE_FILE) VALUES ('Beginners Guide to Python',980,'財務管理','盧秋玲','管理學院','Y','100','完全沒有使用過','1.jpg');
--INSERT INTO BOOK(NAME, PRICE, PROFESSOR, COURSE_NAME, COLLEGE, NOTES_ON, HOW_NEW, MESSAGES, IMAGE_FILE) VALUES ('Insect Behavior',980,'財務管理','盧秋玲','管理學院','Y','100','完全沒有使用過','1.jpg');
--INSERT INTO BOOK(NAME, PRICE, PROFESSOR, COURSE_NAME, COLLEGE, NOTES_ON, HOW_NEW, MESSAGES, IMAGE_FILE) VALUES ('Database Systems',980,'財務管理','盧秋玲','管理學院','Y','100','完全沒有使用過','1.jpg');
--INSERT INTO BOOK(NAME, PRICE, PROFESSOR, COURSE_NAME, COLLEGE, NOTES_ON, HOW_NEW, MESSAGES, IMAGE_FILE) VALUES ('Biology',980,'財務管理','盧秋玲','管理學院','Y','100','完全沒有使用過','1.jpg');
--INSERT INTO BOOK(NAME, PRICE, PROFESSOR, COURSE_NAME, COLLEGE, NOTES_ON, HOW_NEW, MESSAGES, IMAGE_FILE) VALUES ('Principles of Electrical Engineering',980,'財務管理','盧秋玲','管理學院','Y','100','完全沒有使用過','1.jpg');
--INSERT INTO BOOK(NAME, PRICE, PROFESSOR, COURSE_NAME, COLLEGE, NOTES_ON, HOW_NEW, MESSAGES, IMAGE_FILE) VALUES ('Security Engineering',980,'財務管理','盧秋玲','管理學院','Y','100','完全沒有使用過','1.jpg');
--INSERT INTO BOOK(NAME, PRICE, PROFESSOR, COURSE_NAME, COLLEGE, NOTES_ON, HOW_NEW, MESSAGES, IMAGE_FILE) VALUES ('Medical Parasitology',980,'財務管理','盧秋玲','管理學院','Y','100','完全沒有使用過','1.jpg');
--INSERT INTO BOOK(NAME, PRICE, PROFESSOR, COURSE_NAME, COLLEGE, NOTES_ON, HOW_NEW, MESSAGES, IMAGE_FILE) VALUES ('Mayo Clinic Cardiology',980,'財務管理','盧秋玲','管理學院','Y','100','完全沒有使用過','1.jpg');
--INSERT INTO BOOK(NAME, PRICE, PROFESSOR, COURSE_NAME, COLLEGE, NOTES_ON, HOW_NEW, MESSAGES, IMAGE_FILE) VALUES ('Medicinal Chemistry',980,'財務管理','盧秋玲','管理學院','Y','100','完全沒有使用過','1.jpg');
--INSERT INTO BOOK(NAME, PRICE, PROFESSOR, COURSE_NAME, COLLEGE, NOTES_ON, HOW_NEW, MESSAGES, IMAGE_FILE) VALUES ('Organic Chemistry',980,'財務管理','盧秋玲','管理學院','Y','100','完全沒有使用過','1.jpg');
--INSERT INTO BOOK(NAME, PRICE, PROFESSOR, COURSE_NAME, COLLEGE, NOTES_ON, HOW_NEW, MESSAGES, IMAGE_FILE) VALUES ('Physical Science',980,'財務管理','盧秋玲','管理學院','Y','100','完全沒有使用過','1.jpg');
--INSERT INTO BOOK(NAME, PRICE, PROFESSOR, COURSE_NAME, COLLEGE, NOTES_ON, HOW_NEW, MESSAGES, IMAGE_FILE) VALUES ('Leaving Certificate Experiment Book',980,'財務管理','盧秋玲','管理學院','Y','100','完全沒有使用過','1.jpg');





--INSERT INTO MUSIC(NAME, PRICE, LENGTH) VALUES('My Heart Will Go On', '550', '230');
--INSERT INTO MUSIC(NAME, PRICE, LENGTH) VALUES('Take Me Home, Country Road', '550', '230');
--INSERT INTO MUSIC(NAME, PRICE, LENGTH) VALUES('You Raise Me Up', '450', '270');
--INSERT INTO MOVIE(NAME, CATEGORY, YEAR) VALUES('Doctor Strange', 'Action', '2016');
--INSERT INTO MOVIE(NAME, CATEGORY, YEAR) VALUES('Jumanji', 'Adventure', '2017');
--INSERT INTO MOVIE(NAME, CATEGORY, YEAR) VALUES('A Quiet Place', 'Horror', '2018');
